name: Upload jar artifact and create a release

on:
  push:
    branches: ["release"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
      - run: mvn --batch-mode --update-snapshots package
      - run: mkdir staging && cp target/*.jar .
      - name: Get Repo Name
        id: get_repo_name
        run: |
          repo_fullname="${{ github.repository }}"
          repo_name="${repo_fullname##*/}"
          echo "REPO_NAME=${repo_name}" >> $GITHUB_ENV
      - name: Get Tag Name
        id: get_tag_name
        run: |
          tag_name="${{ github.ref }}"
          tag_name="${tag_name#refs/tags/}"
          echo "TAG_NAME=${tag_name}" >> $GITHUB_ENV
#      - uses: actions/upload-artifact@v4
#        with:
#          name: "${{ env.REPO_NAME }}-${{ env.TAG_NAME }}.zip"
      - name: Create Release
        run: |
          echo "Repository Name: $REPO_NAME"
          echo "Tag Name: $TAG_NAME"
          echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_ENV
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "${{ env.REPO_NAME }}-${{ env.TAG_NAME }}.zip"
