name: Create a prerelease

on:
  workflow_run:
    workflows: ["Test and validate Java"]
    types:
      - completed
  workflow_dispatch:

jobs:
  publish-prerelease:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven and publish to GitHub Packages
        run: mvn clean package -DskipTests --settings .github/maven-settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}}

      - name: Delete Old Release
        run: |
          gh release delete pre-release-development --yes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Prerelease
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: pre-release-development
          name: "Pre-release ${{ github.sha }}"
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload JAR file
        uses: softprops/action-gh-release@v2
        with:
          tag_name: pre-release-development
          files: target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}